const constants = {
  USER_REPOSITORY: 'USER_REPOSITORY',
  ROLE_REPOSITORY: 'ROLE_REPOSITORY',
  PERMISSION_REPOSITORY: 'PERMISSION_REPOSITORY',
  DATABASE_CONNECTION: 'DATABASE_CONNECTION',
  ASYNC_CONNECTION: 'ASYNC_CONNECTION',
};

export default constants;
